import {NextResponse} from 'next/server';
import {cookies} from 'next/headers';
import {accessFromRefresh,decrypt,flattenParts} from '@/lib/google';

const clean=(s:string)=>s.replace(/<[^>]*>/g,' ').replace(/&nbsp;|&amp;/g,m=>m==='&amp;'?'&':' ').replace(/\s+/g,' ').trim();
const norm=(s:string)=>clean(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const key=(s:string)=>norm(s).replace(/[^a-z0-9]/g,'');

const strong=['soporte it','soporte informatico','tecnico informatico','técnico informático','helpdesk','help desk','service desk','microinformatica','microinformática','sistemas microinformaticos','sistemas microinformáticos','tecnico de sistemas','técnico de sistemas','administrador de sistemas','sistemas junior','infraestructuras','tecnico de infraestructuras','técnico de infraestructuras','data center','datacenter','cpd','redes','tecnico de redes','técnico de redes','desarrollador web','desarrollo web','programador web','frontend','front end','web junior','soporte tecnico','soporte técnico','hardware','software','windows','incidencias','mantenimiento informatico','mantenimiento informático','bases de datos','ciberseguridad','pdi','preparacion de vehiculos','preparación de vehículos','sistemas multimedia','diagnostico electronico','diagnóstico electrónico'];
const related=['informatica','informática','it ',' it','sistemas','tecnologia','tecnología','redes','web','aplicaciones','microinformaticos','microinformáticos','infraestructura','servidores','office 365','m365','active directory','linux','vmware','javascript','typescript','seo'];
const reject=['control de plagas','limpieza','camarero','camarera','cocina','cocinero','dependiente','dependienta','mozo de almacen','mozo de almacén','repartidor','teleoperador ventas','comercial de seguros','peluquer','esteticista','soldador','fontanero','electricista industrial','carretillero','vigilante de seguridad'];
function relevance(title:string,context:string){const tt=norm(title),all=norm(`${title} ${context}`);if(reject.some(x=>tt.includes(norm(x))))return 0;let n=0;for(const x of strong)if(tt.includes(norm(x)))n+=5;for(const x of related)if(tt.includes(norm(x)))n+=2;if(n===0){for(const x of strong)if(all.includes(norm(x)))n+=1;}return n;}
function scoreText(title:string,context:string){const r=relevance(title,context);let s=48+Math.min(40,r*3);const t=norm(`${title} ${context}`);if(/madrid|remoto|hibrido/.test(t))s+=5;if(/senior|manager|director|jefe de/.test(norm(title)))s-=10;return Math.max(35,Math.min(98,s));}
function money(raw:string){const n=Number(raw.replace(/[^0-9]/g,''));return n>=1000?n:null;}
function salaryFromText(raw:string){const txt=clean(raw);const range=txt.match(/(\d{2,3}(?:[.\s]\d{3})?)\s*€?\s*(?:-|–|a|hasta)\s*(\d{2,3}(?:[.\s]\d{3})?)\s*€(?:\s*(?:brutos?)?(?:\/|al\s+)?año|\s*anuales?)?/i);if(range){const a=money(range[1]),b=money(range[2]);if(a&&b&&a>=12000&&b<=150000)return `${a.toLocaleString('es-ES')}–${b.toLocaleString('es-ES')} €`;}const single=[...txt.matchAll(/(\d{2,3}(?:[.\s]\d{3})?)\s*€(?:\s*(?:brutos?)?(?:\/|al\s+)?año|\s*anuales?)?/gi)].map(m=>money(m[1])).find(n=>n&&n>=12000&&n<=150000);return single?`${single.toLocaleString('es-ES')} €`:null;}
function salaryFor(title:string,body:string){const txt=clean(body);const i=norm(txt).indexOf(norm(title));const segment=i>=0?txt.slice(i,i+1100):txt.slice(0,1100);return salaryFromText(segment);}
function unavailableFromHtml(html:string,status:number,finalUrl:string){if(status===404||status===410)return true;const t=norm(html);if(/oferta no disponible|esta oferta ya no esta disponible|esta oferta ya no está disponible|oferta caducada|oferta finalizada|proceso finalizado|la oferta ha finalizado|ya no puedes inscribirte|ya no es posible inscribirse/.test(t))return true;if(/\/candidate\/job-offer-not-found|\/oferta-no-disponible/i.test(finalUrl))return true;return false;}
async function publicInfo(link:string){try{const r=await fetch(link,{redirect:'follow',cache:'no-store',headers:{'User-Agent':'Mozilla/5.0 AutoJobs/1.0','Accept':'text/html,application/xhtml+xml'}});const html=await r.text();const structured=[...html.matchAll(/"(?:salary|salaryDescription|minimumSalary|maximumSalary|salaryMin|salaryMax)"\s*:\s*"?([^",}<]{2,80})/gi)].map(m=>m[1]).join(' ');return{salary:salaryFromText(`${structured} ${html}`),available:!unavailableFromHtml(html,r.status,r.url)};}catch{return{salary:null,available:true};}}
function hrefs(body:string){const out:{title:string,link:string}[]=[];for(const m of body.matchAll(/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)){const link=m[1].replace(/&amp;/g,'&'),title=clean(m[2]);if(/link\.push\.infojobs\.net/i.test(link)&&title&&title.length>3&&!/ver más|gestionar|eliminar|opinión|privacidad|baja/i.test(title))out.push({title,link});}for(const m of body.matchAll(/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/g)){const title=clean(m[1]),link=m[2];if(/link\.push\.infojobs\.net/i.test(link)&&!/ver más|gestionar|eliminar|opinión|privacidad|baja/i.test(title))out.push({title,link});}return out;}
function appTitle(subject:string,snippet:string,body:string){const t=clean(`${snippet} ${body}`).slice(0,1400);let m=t.match(/te has inscrito (?:en|a) la oferta\s+(.+?)(?:\s+puedes seguir|\s+y\s+[A-ZÁÉÍÓÚÑ]|$)/i);if(m?.[1])return clean(m[1]);m=t.match(/proceso para\s+(.+?)\s+ha finalizado/i);if(m?.[1])return clean(m[1]);m=t.match(/candidatura[^.]*?\s+(.+?)(?:\s+ver candidatura|$)/i);return m?.[1]?clean(m[1]):subject;}
async function gmail(access:string,q:string,max=30){const lr=await fetch(`https://gmail.googleapis.com/gmail/v1/users/me/messages?q=${encodeURIComponent(q)}&maxResults=${max}`,{headers:{Authorization:`Bearer ${access}`},cache:'no-store'});if(!lr.ok)return[];const list=await lr.json();const out:any[]=[];for(const it of (list.messages||[])){const r=await fetch(`https://gmail.googleapis.com/gmail/v1/users/me/messages/${it.id}?format=full`,{headers:{Authorization:`Bearer ${access}`},cache:'no-store'});if(!r.ok)continue;const m=await r.json(),hs=Object.fromEntries((m.payload?.headers||[]).map((h:any)=>[h.name.toLowerCase(),h.value]));out.push({id:it.id,subject:hs.subject||'',date:hs.date||'',snippet:m.snippet||'',body:flattenParts(m.payload)});}return out;}
export async function GET(){try{const jar=await cookies(),enc=jar.get('autojobs_google_refresh')?.value;if(!enc)return NextResponse.json({connected:false,jobs:[],applications:[]});const access=(await accessFromRefresh(decrypt(enc))).access_token;
const alertMails=await gmail(access,'from:ofertas@push.infojobs.net newer_than:60d',35);const appMails=await gmail(access,'(from:pushinfojobs@comms.infojobs.net OR from:pushinfojobs@notify.infojobs.net) newer_than:120d',40);
const applications:any[]=[];for(const m of appMails){const lower=norm(`${m.subject} ${m.snippet} ${m.body}`);let status='Novedades';if(/te has inscrito a una oferta|te has inscrito en la oferta/.test(lower))status='Inscrito';if(/proceso ha finalizado|proceso para.+ha finalizado|este proceso ha finalizado/.test(lower))status='Finalizado';const title=appTitle(m.subject,m.snippet,m.body);applications.push({id:m.id,title,status,date:m.date});}
const statusBy=new Map<string,string>();for(const a of applications){const k=key(a.title);if(k)statusBy.set(k,a.status);}
const seen=new Set<string>(),jobs:any[]=[];for(const m of alertMails){const offers=hrefs(m.body);for(const o of offers){const k=key(o.title);if(!k||seen.has(k))continue;const context=`${m.subject} ${m.snippet} ${m.body}`;const rel=relevance(o.title,context);if(rel<2)continue;seen.add(k);let state='Nueva';for(const [ak,st] of statusBy){if(ak.includes(k)||k.includes(ak)){state=st;break;}}jobs.push({id:`${m.id}-${jobs.length}`,title:o.title,link:o.link,score:scoreText(o.title,context),salary:salaryFor(o.title,m.body),date:m.date,status:state,relevance:rel,available:true});}}
const checks=jobs.slice(0,15);await Promise.all(checks.map(async j=>{const info=await publicInfo(j.link);if(!j.salary)j.salary=info.salary;j.available=info.available;}));
const active=jobs.filter(j=>j.available!==false);active.sort((a,b)=>(a.status==='Nueva'?0:1)-(b.status==='Nueva'?0:1)||b.relevance-a.relevance||b.score-a.score);const appUnique=[...new Map(applications.map(a=>[key(a.title),a])).values()].filter((a:any)=>key(a.title));return NextResponse.json({connected:true,jobs:active,applications:appUnique});}catch(e:any){return NextResponse.json({connected:false,jobs:[],applications:[],error:e?.message||'Error leyendo Gmail'},{status:500});}}
