import {NextRequest,NextResponse} from 'next/server';
const clean=(s:string)=>String(s||'').replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&#39;|&apos;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g,' ').trim();
const norm=(s:string)=>clean(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const API='https://api.infojobs.net/api/9/offer';
const SEARCHES=[{category:'Soporte IT',terms:['soporte it','helpdesk','service desk','tecnico informatico','soporte tecnico','microinformatica']},{category:'Desarrollo Web',terms:['desarrollador web','frontend','javascript','react','wordpress']},{category:'Infraestructura / Sistemas',terms:['tecnico sistemas','administrador sistemas','infraestructura','sysadmin']},{category:'Ciberseguridad',terms:['ciberseguridad','SOC','SIEM','cybersecurity']},{category:'IA / Automatización',terms:['inteligencia artificial','automatizacion','LLM','machine learning']},{category:'Redes',terms:['redes','Cisco','network','NOC']}];
const AREAS=SEARCHES.map(x=>x.category),IT_EXPERIENCE=['no-requerida','al-menos-1-ano','al-menos-2-anos','al-menos-3-anos'],TTL=10*60*1000;
type Job={id:string;title:string;link:string;score:number;salary:string|null;date:string;timestamp:number;status:string;category:string;categories:string[];city?:string;company?:string;experience?:string;source:string};
const g=globalThis as typeof globalThis&{__autojobsStableV5?:{at:number;jobs:Job[]}};
function years(v:any){const t=norm(v?.value||v||'');if(!t||/no requerida|sin experiencia/.test(t))return 0;const m=t.match(/(\d+)/);return m?Number(m[1]):99;}
function primaryCategory(title:string,fallback:string){const t=norm(title);if(/soporte|help.?desk|service desk|tecnico informatico|microinformat|desktop support|it support/.test(t))return'Soporte IT';if(/desarroll|programador|frontend|full.?stack|javascript|typescript|react|wordpress|php|node/.test(t))return'Desarrollo Web';if(/ciber|cyber|soc\b|siem|security|pentest/.test(t))return'Ciberseguridad';if(/inteligencia artificial|machine learning|\bia\b|\bai\b|automatiz|prompt|llm/.test(t))return'IA / Automatización';if(/redes|network|router|switch|cisco|noc\b/.test(t))return'Redes';if(/infraestruct|sistemas|sysadmin|administrador|servidor|data center|cpd|vmware|active directory|linux|azure|aws/.test(t))return'Infraestructura / Sistemas';return fallback;}
function badTitle(t:string){return /senior|\bsr\b|lead\b|manager\b|director\b|jefe de|head of/.test(norm(t));}
function salary(o:any){if(o.salaryDescription)return clean(o.salaryDescription);const a=clean(o.salaryMin?.value||''),b=clean(o.salaryMax?.value||''),p=clean(o.salaryPeriod?.value||'');if(a&&b&&a!==b)return`${a}–${b}${p?` · ${p}`:''}`;return a?`${a}${p?` · ${p}`:''}`:null;}
function score(o:any,c:string){let s=55;const t=norm(`${o.title||''} ${o.requirementMin||''}`);if(/junior|sin experiencia|no requerida|primer empleo|nivel 1|n1/.test(t))s+=12;if(/madrid/.test(norm(`${o.city||''} ${o.province?.value||''}`)))s+=5;if(c==='Soporte IT'&&/soporte|help.?desk|service desk|tecnico informatico/.test(t))s+=10;if(c==='Desarrollo Web'&&/web|frontend|javascript|react|php|wordpress/.test(t))s+=10;if(c==='Infraestructura / Sistemas'&&/sistemas|infraestruct|servidor|vmware|active directory|azure/.test(t))s+=10;if(c==='Ciberseguridad'&&/ciber|cyber|soc|siem|security/.test(t))s+=10;if(c==='IA / Automatización'&&/inteligencia artificial|\bia\b|automat|llm|machine learning/.test(t))s+=10;if(c==='Redes'&&/redes|network|cisco|router|switch/.test(t))s+=10;return Math.min(98,s);}
function authHeader(){const id=process.env.INFOJOBS_CLIENT_ID?.trim(),secret=process.env.INFOJOBS_CLIENT_SECRET?.trim();if(!id||!secret)return null;return`Basic ${Buffer.from(`${id}:${secret}`).toString('base64')}`;}
async function api(params:Record<string,string|string[]>){const auth=authHeader();if(!auth)throw new Error('INFOJOBS_CREDENTIALS_MISSING');const u=new URL(API);for(const[k,v]of Object.entries(params)){if(Array.isArray(v))for(const x of v)u.searchParams.append(k,x);else if(v)u.searchParams.set(k,v);}const r=await fetch(u,{cache:'no-store',headers:{Authorization:auth,Accept:'application/json','User-Agent':'AutoJobs/5.0'}});const text=await r.text();if(!r.ok)throw new Error(`INFOJOBS_API_${r.status}`);try{return JSON.parse(text)}catch{throw new Error('INFOJOBS_API_INVALID_JSON')}}
function mapOffer(o:any,sourceCategory:string):Job|null{if(!o?.id||!o?.title||!o?.link||badTitle(o.title)||years(o.experienceMin)>3)return null;const c=primaryCategory(o.title,sourceCategory),published=o.updated||o.published||new Date().toISOString();return{id:`ij-${o.id}`,title:clean(o.title),link:o.link,score:score(o,c),salary:salary(o),date:published,timestamp:new Date(published).getTime()||0,status:'Nueva',category:c,categories:[sourceCategory,c].filter((v,i,a)=>a.indexOf(v)===i),city:clean(o.city||''),company:clean(o.author?.name||''),experience:clean(o.experienceMin?.value||''),source:'infojobs-api'};}
async function queryPages(q:string|undefined,category:string,experience:string[]|undefined,maxPages=2){const out:Job[]=[];for(let page=1;page<=maxPages;page++){const params:Record<string,string|string[]>={province:'madrid',order:'updated-desc',sinceDate:'_15_DAYS',maxResults:'50',page:String(page)};if(q)params.q=q;if(experience)params.experienceMin=experience;const d=await api(params);for(const o of d.offers||[]){const j=mapOffer(o,category);if(j)out.push(j)}if(!d.totalPages||page>=d.totalPages)break}return out;}
async function buildApiFeed(force=false){if(!force&&g.__autojobsStableV5&&Date.now()-g.__autojobsStableV5.at<TTL)return g.__autojobsStableV5.jobs;const generalPromise=queryPages(undefined,'General',['no-requerida'],2),jobsPromises=SEARCHES.flatMap(s=>s.terms.map(term=>queryPages(term,s.category,IT_EXPERIENCE,1)));const[general,...groups]=await Promise.all([generalPromise,...jobsPromises]);const by=new Map<string,Job>();for(const j of[...general,...groups.flat()]){const old=by.get(j.id);if(!old)by.set(j.id,j);else by.set(j.id,{...old,category:primaryCategory(old.title,old.category),categories:[...new Set([...old.categories,...j.categories])],score:Math.max(old.score,j.score),salary:old.salary||j.salary})}const jobs=[...by.values()].sort((a,b)=>b.timestamp-a.timestamp||b.score-a.score);g.__autojobsStableV5={at:Date.now(),jobs};return jobs;}
export async function GET(req:NextRequest){const force=req.nextUrl.searchParams.get('refresh')==='1';try{const jobs=await buildApiFeed(force),counts:Record<string,number>={Todas:jobs.length};for(const a of AREAS)counts[a]=jobs.filter(j=>j.categories.includes(a)).length;return NextResponse.json({jobs,counts,source:'infojobs-api',providerStatus:'ok',providerError:null,filters:{location:'Madrid',generalExperience:'Sin experiencia requerida',itExperience:'0–3 años',period:'Últimos 15 días',sort:'Más recientes primero',cache:'10 minutos'}})}catch(e:any){const error=e?.message||'INFOJOBS_API_ERROR',status=error==='INFOJOBS_CREDENTIALS_MISSING'?'missing_credentials':'provider_error',counts:Record<string,number>={Todas:0};for(const a of AREAS)counts[a]=0;return NextResponse.json({jobs:[],counts,source:'infojobs-api',providerStatus:status,providerError:error,filters:{location:'Madrid',generalExperience:'Sin experiencia requerida',itExperience:'0–3 años',period:'Últimos 15 días',sort:'Más recientes primero',cache:'10 minutos'}},{status:503})}}
