import {NextRequest,NextResponse} from 'next/server';

const clean=(s:string)=>String(s||'').replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&#39;|&apos;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g,' ').trim();
const norm=(s:string)=>clean(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const key=(s:string)=>norm(s).replace(/[^a-z0-9]/g,'');
const SEARCHES=[
 {category:'Soporte IT',keywords:['soporte it','tecnico soporte','helpdesk','service desk','tecnico informatico','microinformatica','it support']},
 {category:'Desarrollo Web',keywords:['desarrollador web','programador web','frontend','backend','full stack','wordpress','javascript']},
 {category:'Infraestructura / Sistemas',keywords:['tecnico sistemas','administrador sistemas','sistemas informaticos','sysadmin','infraestructura it','data center','cloud']},
 {category:'Ciberseguridad',keywords:['ciberseguridad','cybersecurity','soc','analista seguridad','seguridad informatica','siem','security analyst']},
 {category:'IA / Automatización',keywords:['data scientist','data science','data engineer','machine learning','inteligencia artificial','artificial intelligence','ai engineer','genai','llm','rpa']},
 {category:'Redes',keywords:['redes informaticas','tecnico redes','network engineer','cisco','noc','comunicaciones it','network technician']}
];
const AREAS=SEARCHES.map(x=>x.category),TTL=10*60*1000;
type Job={id:string;title:string;link:string;score:number;salary:string|null;date:string;timestamp:number;rank:number;status:string;category:string;categories:string[];city?:string;company?:string;experience?:string;source:string};
const g=globalThis as typeof globalThis&{__autojobsWebFeedV8?:{at:number;jobs:Job[]}};

const excludedTitle=/\b(?:cocin(?:ero|era)|camarer(?:o|a)|bartender|repartidor|mozo|almacen|farmaceut|enfermer|abogad|dependient|pescader|operario|conductor|recepcionista|secretari|administrativ|logistic|rrhh|recursos humanos|limpieza|trabajador social|menores|montaje industrial|mecanico|teleoperador|call center|preventa|presales)\b|jefe.? de obra|encargad[oa].? de obra|obra civil|instalador.? electric|comercial\b|ventas\b|asesor.? comercial|curso\b|formacion\b/i;
function isClearlyNonIT(title:string){return excludedTitle.test(norm(title));}
function primaryCategory(title:string,fallback='General'){
 const t=norm(title);
 if(isClearlyNonIT(title))return'General';
 if(/soporte (?:it|ti|tecnico|informatico)|tecnico.? (?:de )?soporte(?:\s+(?:it|ti|tecnico|informatico|l1|l2|n1|n2))?|help.?desk|service desk|tecnico.? informatico|microinformat|desktop support|it support|cau\b/.test(t))return'Soporte IT';
 if(/data scientist|data science|data engineer|machine learning|ml engineer|inteligencia artificial|artificial intelligence|\bai\b.*\b(?:engineer|data)\b|\bia engineer\b|generative ai|genai|prompt engineer|\bllm\b|\brpa\b/.test(t))return'IA / Automatización';
 if(/desarroll(?:ador|o)|programador|frontend|front end|backend|full.?stack|javascript|typescript|react|wordpress|php|node|web developer|software developer|java developer|python developer|\.net developer/.test(t))return'Desarrollo Web';
 if(/ciber|cyber|soc\b|siem|security analyst|pentest|seguridad informatica/.test(t))return'Ciberseguridad';
 if(/redes informatic|tecnico.? redes|network engineer|network technician|router|switch|cisco|noc\b|comunicaciones it/.test(t))return'Redes';
 if(/infraestruct|sistemas informatic|sysadmin|administrador de sistemas|servidor|data center|datacenter|cpd|vmware|active directory|linux|azure|aws|cloud engineer|devops/.test(t))return'Infraestructura / Sistemas';
 return fallback;
}
function matchesCategory(title:string,category:string){if(isClearlyNonIT(title))return false;const c=primaryCategory(title,'General');if(c===category)return true;const t=norm(title);if(category==='Soporte IT')return /tecnico.? (?:de )?(?:soporte|sistemas|it)|operador.? informatico|puesto de usuario/.test(t);if(category==='Desarrollo Web')return /web developer|\.net|java developer|angular|vue|python developer/.test(t);if(category==='Infraestructura / Sistemas')return /tecnico.? sistemas|administrador.? sistemas|cloud engineer|devops/.test(t);if(category==='Ciberseguridad')return /analista.? seguridad|security analyst/.test(t);if(category==='IA / Automatización')return /data.?scientist|data science|data engineer|machine learning|ml engineer|generative ai|genai|rpa developer|ai engineer|ia engineer/.test(t);if(category==='Redes')return /tecnico.? redes|network engineer|network technician|noc\b/.test(t);return false;}
function tooSenior(title:string,body=''){const titleNorm=norm(title),t=norm(`${title} ${body}`);if(/senior|\bsr\b|lead\b|manager\b|director\b|head of|arquitecto|architect\b|coordinador/.test(titleNorm))return true;if(/\b(?:bruselas|brussels|paris|parís|lisboa|lisbon|berlin|berlín|londres|london|dublin|dublín)\b/.test(titleNorm))return true;if(/(?:minimo|al menos|mas de|experiencia(?: minima)?(?: de)?)\s*(?:4|5|6|7|8|9|10)\s*(?:anos|años)/.test(t))return true;if(/(?:4|5|6|7|8|9|10)\+?\s*(?:anos|años)\s+de experiencia/.test(t))return true;return false;}
function scoreTitle(title:string,body=''){const t=norm(`${title} ${body}`);let s=48;if(/madrid|remoto|hibrido/.test(t))s+=5;if(/junior|primer empleo|sin experiencia|nivel 1|n1|practicas|beca/.test(t))s+=12;if(primaryCategory(title,'General')!=='General')s+=18;return Math.max(35,Math.min(98,s));}
function salaryFromText(raw:string){const txt=clean(raw),money=(x:string)=>Number(x.replace(/[^0-9]/g,''));const kRange=txt.match(/\b(\d{2,3})\s*k\s*(?:-|–|a|hasta)\s*(\d{2,3})\s*k\b/i);if(kRange){const a=Number(kRange[1])*1000,b=Number(kRange[2])*1000;if(a>=12000&&b<=150000&&a<=b)return a===b?`${a.toLocaleString('es-ES')} €`:`${a.toLocaleString('es-ES')}–${b.toLocaleString('es-ES')} €`;}const k=txt.match(/\b(?:hasta\s+)?(\d{2,3})\s*k\b/i);if(k){const n=Number(k[1])*1000;if(n>=12000&&n<=150000)return`${n.toLocaleString('es-ES')} €`;}const range=txt.match(/(\d{2,3}(?:[.\s]\d{3})?)\s*€?\s*(?:-|–|a|hasta)\s*(\d{2,3}(?:[.\s]\d{3})?)\s*€/i);if(range){const a=money(range[1]),b=money(range[2]);if(a>=12000&&b>=12000&&a<=150000&&b<=150000){if(a===b)return`${a.toLocaleString('es-ES')} €`;if(a<b)return`${a.toLocaleString('es-ES')}–${b.toLocaleString('es-ES')} €`;}}const annual=[...txt.matchAll(/(\d{2,3}(?:[.\s]\d{3})?)\s*€/gi)].map(m=>money(m[1])).find(n=>n>=12000&&n<=150000);return annual?`${annual.toLocaleString('es-ES')} €`:null;}
function salaryBelowMinimum(salary:string|null){if(!salary)return false;const nums=[...salary.matchAll(/\d{2,3}(?:\.\d{3})?/g)].map(m=>Number(m[0].replace(/\./g,''))).filter(n=>n>=12000);return nums.length>0&&Math.max(...nums)<20000;}
function parsedTimestamp(raw:string){const original=String(raw||''),t=norm(original),now=Date.now(),valid=(v:number)=>Number.isFinite(v)&&v<=now+3600000&&v>=now-120*86400000?v:0;let m=original.match(/(?:datePublished|datetime)["'\s:=]+["']?(\d{4}-\d{2}-\d{2}(?:T[^"'\s<]+)?)/i);if(m){const v=valid(Date.parse(m[1]));if(v)return v;}m=t.match(/hace\s+(\d+)\s*(?:min|minutos?)/);if(m)return valid(now-Number(m[1])*60000);m=t.match(/hace\s+(\d+)\s*(?:h|horas?)/);if(m)return valid(now-Number(m[1])*3600000);m=t.match(/hace\s+(\d+)\s*(?:d|dias?)/);if(m)return valid(now-Number(m[1])*86400000);m=t.match(/hace\s+(\d+)\s*(?:sem|semanas?)/);if(m)return valid(now-Number(m[1])*7*86400000);const day=new Date();day.setUTCHours(12,0,0,0);if(/\bhoy\b/.test(t))return day.getTime();if(/\bayer\b/.test(t))return day.getTime()-86400000;return 0;}
function experienceFromText(raw:string){const t=norm(raw);if(/sin experiencia/.test(t))return'Sin experiencia';let m=t.match(/(?:minimo|al menos|experiencia(?: minima)?(?: de)?|se requieren?)\s*(\d{1,2})\s*(?:anos|años)/);if(!m)m=t.match(/\b(\d{1,2})\s*(?:anos|años)\s+de experiencia\b/);if(!m)return'';const n=Number(m[1]);return n<=3?`${n} ${n===1?'año':'años'}`:'';}
function offerId(link:string,title:string){return link.match(/\/of-([a-z0-9]+)/i)?.[1]||key(title);}
function normalizeLink(raw:string){let link=raw.replace(/&amp;/g,'&').trim();if(/^\/www\.infojobs\.net\//i.test(link))link=`https:/${link}`;else if(link.startsWith('//'))link=`https:${link}`;else if(link.startsWith('/'))link=`https://www.infojobs.net${link}`;else if(/^www\.infojobs\.net\//i.test(link))link=`https://${link}`;return link.replace('https://www.infojobs.net//www.infojobs.net/','https://www.infojobs.net/');}
function validInfoJobsLink(link:string){try{const u=new URL(link);return /^(?:www\.)?infojobs\.net$/i.test(u.hostname)&&/\/of-[a-z0-9]+/i.test(u.pathname);}catch{return false;}}
const madridPlaces=/\/(madrid|alcobendas|getafe|leganes|pozuelo|las-rozas|alcorcon|mostoles|coslada|san-sebastian-de-los-reyes|tres-cantos|torrejon|fuenlabrada|parla|majadahonda|alcala-de-henares|rivas-vaciamadrid|san-fernando-de-henares)\//;
function madridLink(link:string){try{return madridPlaces.test(norm(new URL(link).pathname));}catch{return false;}}
function extractCity(link:string){try{const p=new URL(link).pathname.split('/').filter(Boolean)[0]||'madrid';return p.split('-').map(x=>x.charAt(0).toUpperCase()+x.slice(1)).join(' ');}catch{return'Madrid';}}
function extractCard(html:string,idx:number){const candidates=[{open:'<article',close:'</article>'},{open:'<li',close:'</li>'}].map(x=>({...x,start:html.lastIndexOf(x.open,idx)})).filter(x=>x.start>=0).sort((a,b)=>b.start-a.start);for(const c of candidates){const end=html.indexOf(c.close,idx);if(end>idx&&end-c.start<12000)return html.slice(c.start,end+c.close.length);}return html.slice(Math.max(0,idx-500),idx+3000);}
function searchUrl(keyword:string|undefined,page:number){const u=new URL('https://www.infojobs.net/ofertas-trabajo');u.searchParams.set('provinceIds','33');u.searchParams.set('sortBy','PUBLICATION_DATE');u.searchParams.set('page',String(page));if(keyword)u.searchParams.set('keyword',keyword);return u.toString();}
async function fetchSearch(keyword:string|undefined,sourceCategory:string,page:number){const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),7000);try{const r=await fetch(searchUrl(keyword,page),{cache:'no-store',redirect:'follow',signal:ctrl.signal,headers:{'User-Agent':'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1','Accept':'text/html,application/xhtml+xml','Accept-Language':'es-ES,es;q=0.9'}});if(!r.ok)throw new Error(`INFOJOBS_WEB_${r.status}`);const html=await r.text(),matches=[...html.matchAll(/<a[^>]+href=["']([^"']*\/of-[^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)],out:Job[]=[],seen=new Set<string>();let order=(page-1)*100;for(const m of matches){const link=normalizeLink(m[1]);if(!validInfoJobsLink(link)||!madridLink(link))continue;const title=clean(m[2]);if(!title||title.length<4||title.length>180||/^(ver oferta|ver más|guardar|inscribirme)$/i.test(title)||isClearlyNonIT(title))continue;if(sourceCategory!=='General'&&!matchesCategory(title,sourceCategory))continue;const id=offerId(link,title);if(seen.has(id))continue;const idx=m.index||0,block=extractCard(html,idx),text=clean(block);if(tooSenior(title,text))continue;const primary=primaryCategory(title,sourceCategory);if(primary==='General')continue;const salary=salaryFromText(`${title} ${text}`);if(salaryBelowMinimum(salary))continue;seen.add(id);const ts=parsedTimestamp(block),rank=order++;out.push({id:`ijw-${id}`,title,link,score:scoreTitle(title,text),salary,date:ts?new Date(ts).toISOString():'',timestamp:ts,rank,status:'Nueva',category:primary,categories:[sourceCategory,primary].filter(v=>v!=='General').filter((v,i,a)=>a.indexOf(v)===i),city:extractCity(link),company:'',experience:experienceFromText(`${title} ${text}`),source:'infojobs-web'});}return out;}finally{clearTimeout(timer);}}
async function buildFeed(force=false){if(!force&&g.__autojobsWebFeedV8&&Date.now()-g.__autojobsWebFeedV8.at<TTL)return g.__autojobsWebFeedV8.jobs;const requests:Promise<Job[]>[]=[];for(let p=1;p<=3;p++)requests.push(fetchSearch(undefined,'General',p));for(const s of SEARCHES)for(const keyword of s.keywords)for(let p=1;p<=3;p++)requests.push(fetchSearch(keyword,s.category,p));const results=await Promise.allSettled(requests),all:Job[]=[];for(const r of results)if(r.status==='fulfilled')all.push(...r.value);const by=new Map<string,Job>();for(const j of all){const id=offerId(j.link,j.title),old=by.get(id);if(!old){by.set(id,j);continue;}const cats=[...(old.categories||[]),...(j.categories||[])].filter((v,i,a)=>a.indexOf(v)===i),primary=primaryCategory(j.title,old.category==='General'?j.category:old.category),newTs=Math.max(old.timestamp,j.timestamp);by.set(id,{...old,category:primary,categories:cats,score:Math.max(old.score,j.score),salary:old.salary||j.salary,experience:old.experience||j.experience,timestamp:newTs,date:newTs?new Date(newTs).toISOString():'',rank:Math.min(old.rank,j.rank)});}const jobs=[...by.values()].filter(j=>j.category!=='General'&&validInfoJobsLink(j.link)&&!salaryBelowMinimum(j.salary)).sort((a,b)=>{const ak=a.timestamp>0,bk=b.timestamp>0;if(ak!==bk)return bk?1:-1;if(a.timestamp!==b.timestamp)return b.timestamp-a.timestamp;if(a.rank!==b.rank)return a.rank-b.rank;return b.score-a.score;});if(!jobs.length){if(g.__autojobsWebFeedV8?.jobs?.length)return g.__autojobsWebFeedV8.jobs;const failures=results.filter(r=>r.status==='rejected').map(r=>(r as PromiseRejectedResult).reason?.message||'error');throw new Error(failures[0]||'INFOJOBS_WEB_EMPTY');}g.__autojobsWebFeedV8={at:Date.now(),jobs};return jobs;}
export async function GET(req:NextRequest){const force=req.nextUrl.searchParams.get('refresh')==='1';try{const jobs=await buildFeed(force),counts:Record<string,number>={Todas:jobs.length};for(const a of AREAS)counts[a]=jobs.filter(j=>j.categories.includes(a)||j.category===a).length;return NextResponse.json({jobs,counts,source:'infojobs-web',providerStatus:'ok',providerError:null,filters:{location:'Madrid',sort:'Más recientes primero',source:'Búsquedas múltiples directas en InfoJobs',pagesPerSearch:3,minimumSalary:'20.000 € cuando está indicado',experience:'0–3 años cuando puede verificarse',cache:'10 minutos'}});}catch(e:any){const counts:Record<string,number>={Todas:0};for(const a of AREAS)counts[a]=0;return NextResponse.json({jobs:[],counts,source:'infojobs-web',providerStatus:'provider_error',providerError:e?.message||'INFOJOBS_WEB_ERROR',filters:{location:'Madrid',sort:'Más recientes primero',source:'Búsquedas múltiples directas en InfoJobs',pagesPerSearch:3,minimumSalary:'20.000 € cuando está indicado',experience:'0–3 años cuando puede verificarse',cache:'10 minutos'}},{status:502});}}